Galleria/Galleria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gallery/', include('gallery.urls')),
    path('users/', include('users.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Galleria/gallery/urls.py
from django.urls import path
from . views import *

#path(request osa ja url, nimi jolla me viitataan views.pyssä, viitataan html/views?)
#gallery:functio sivuun johon haluaan
app_name = 'gallery'
urlpatterns = [
    #index
    path('', display_images, name = 'display_images'),
    #upload sivu
    path('image_upload', image_upload, name = 'image_upload'),
    #Delete id perusteella
    path('<pk>/delete/', PostDeleteView.as_view()),
]

Galleria/users/urls.py
from django.urls import  path
from . views import *

#MITÄ VITTUA MÄ TEEN :D
#auth_view.LoginView.as_view(), name='login'
app_name = 'users'
urlpatterns = [
    path('login/', login_request, name='login'),
    path('register/', register_request, name='register'),
    path('logout/', logout_request, name='logout'),
]

Galleria/gallery/models.py
from django.db import models
#ei tarvita varmaa

from PIL import Image
from django.conf import settings
from stdimage import StdImageField, JPEGField
from stdimage.validators import MinSizeValidator
# Create your models here.

class Post(models.Model):
    #Meillä on neljä kuvaa StdImagen avulla yhdesä. Kaikki kuuluu samaan juttun
    image = JPEGField(upload_to='images/', blank=False, variations={
        'large':(800, 600),
        'thumbnail':(300, 300, True),
        'medium':(400,600),}, delete_orphans=True, validators=[MinSizeValidator(300, 300)])
    description = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    mod_date = models.DateTimeField('date modified', auto_now=True)
    submitter = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

Galleria/users/models.py
from django.db import models

# Create your models here.

Galleria/gallery/forms.py
from django import forms
from .models import Post

class UploadForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['description', 'image']

Galleria/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

Galleria/gallery/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Post
from .forms import UploadForm
from django.contrib.auth.decorators import login_required
from django.utils import timezone
# Create your views here.

#app/urls viittaa nimet tänne ja miten ne toimii

def display_images(request):
    if request.method == 'GET':
        posts = Post.objects.all()
        return render(request, 'gallery/index.html', {'posts' : posts})

@login_required
def image_upload(request):
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.submitter = request.user
            post.pub_date = timezone.now()
            post.save()
            return redirect('gallery:display_images')
    else:
        form = UploadForm()
    return render(request, 'gallery/upload.html', {'form' : form})


#kuvan poisto form
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy
class PostDeleteView(DeleteView):
    model = Post
    success_url = '/gallery/'

Galleria/users/views.py
from django.shortcuts import  render, redirect
from .forms import NewUserForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
# Create your views here.

def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("gallery:display_images")
    else:
        form = NewUserForm()
    return render(request, "users/register.html", {"register_form":form})
    
def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("gallery:display_images")
    else:
        form = AuthenticationForm()
    return render(request, "users/login.html", {"login_form":form})

def logout_request(request):
    logout(request)
    return redirect("users:login")

Galleria/Galleria/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
      crossorigin="anonymous"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates&family=Montserrat:wght@400;600&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/2fe4789981.js" crossorigin="anonymous"></script>
    <link href="/static/style.css" rel="stylesheet">
    <link rel="icon" href="/static/favicon.svg" type="image/x-icon">
    <title>BitLouvre</title>
</head>
<body>
    <header class="jumbotron">
      <div class="header-filter p-3">
      <div class="border-left border-white">
        <h1 class="text-center">BitLouvre</h1>
      </div>
      <p class="text-center slogan">Your number one location for sophisticated animetytys</p>
    </div>
    </header>
    <nav class="navbar navbar-expand-sm justify-content-center sticky-top" style="padding: 0;">
      <div class="nav-blur-filter"></div>
     
        <ul id="navbar-list" class="navbar-nav">
          <li>
            {% if user.is_authenticated %}
            <a class="nav-link disabled navbar-left" href="#">Hello {{user.username}}!</a>
            {% endif %}
            
            <a class="icon" href="javascript:void(0);" onclick="dropdown()">
            <i class="fas fa-bars"></i>
          </a></li>
          <li class="nav-item"><a class="nav-link" href="{% url "gallery:display_images" %}">Gallery</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url "gallery:image_upload" %}">Upload</a></li>
          
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url "users:logout" %}">Log Out</a>
          </li>
          
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url "users:login" %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <main class="container justify-content-center">
    {% block content %}
    {% endblock content %}
    </main>
    <footer class="mt-auto">
      <ul>
        <li>Made by Erkka, Hannu ja Axe</a></li> 
      </ul>
      <p class="copyright">BitLouvre © 2021</p>
    </footer>
  </div>
</body>
  <script>
    function dropdown() {
      var x = document.getElementById("navbar-list");
      if (x.className == "navbar-nav") {
        x.className += " dropdown";
      } else { 
        x.className = "navbar-nav";
      }
    }
  </script>

</html>

Galleria/gallery/templates/gallery/index.html
{% extends "base.html" %}

{% block content %}
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.css">
</head>


<div id="gallery-template" class="template">
    <div class="row">
    {% for post in posts %}
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-2 gallery_img_div" style="overflow:hidden; padding-top: calc(var(--bs-gutter-x)/ 2); padding-bottom: calc(var(--bs-gutter-x)/ 2);">
            <p>{{ post.description }}</p>
            <a class="lightbox" href="{{ post.image.url}}">
                <img src="{{ post.image.thumbnail.url}}" alt="{{ post.description }}"/>
            </a>
            <form action="{{post.id}}/delete/">
                <button class="indexbutton" href="{{post.id}}/delete/">Delete</button>
            </form>
        </div>
    {% endfor %}
    </div>
</div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
<script>
    baguetteBox.run('.template');
    baguetteBox.run('.template', {
        captions: function(element) {
            return element.getElementsByTagName('img')[0].alt;
        }
    });
</script>
{% endblock %}

Galleria/gallery/templates/gallery/post_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<div id="row">
    <div class="deletediv">
        <form method="post">
            {% csrf_token %}
            {% if user == post.submitter %}
            <p>Are you sure you want to delete this image?</p>
            <img src="{{ post.image.url}}" class="border border-secondary"/>
            <div id="deletebuttons">
                <a style="text-decoration:none" href="{% url "gallery:display_images" %}">
                    <button type="button" class="btn btn-outline-danger">Cancel</button>
                </a>
                <button class="btn btn-outline-success">Confirm</button>
            </div>
            {% else %}
            <h2>You are not the owner of this picture</h2>
            <img src="{{ post.image.url}}" class="border border-secondary"/>
            <a href="{% url "gallery:display_images" %}">
                <br>
                <br>
                <button type="button" class="btn btn-dark btn-lg">Go back to the main page</button>
            </a>
            {% endif %}
        </form> 
    </div>
</div>
{% endblock %}

Galleria/gallery/templates/gallery/success.html
{% extends "base.html" %}

{% block content %}
<div class="template">
    <div class="form-container">
        <a href="{% url 'gallery:image_upload' %}">
            <button type="button" class="btn btn-dark">Upload new picture</button>
        </a>
        <a href="{% url 'gallery:display_images' %}">
            <button type="button" class="btn btn-dark btn-lg">Go back to gallery</button>
        </a>
    </div>
</div>
{% endblock %}

Galleria/gallery/templates/gallery/upload.html
{% extends "base.html" %}

{% block content %}
<div class="template">
    <div class="form-container">
        <h2>Upload</h2>
        <br>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-dark btn-lg">Upload</button>
        </form>
        <br>
        <p><a href="{% url 'gallery:display_images' %}">Go back to main page</a></p>
    </div>
</div>
{% endblock %}

Galleria/users/templates/users/login.html
{% extends "base.html" %}

{% block content %}
<div class="template">
    <div class="form-container">
        <h2>Login</h2>
        <br>
        <form method="POST">
            {% csrf_token %}
            {{ login_form.as_p }}
            <br>
            <button type="submit" class="btn btn-dark btn-lg">Login</button>
        </form>
        <p class="text-center">Don't have an account? <a href="{% url "users:register" %}">Create an account</a>.</p>
    </div>
</div>
{% endblock %}

Galleria/users/templates/users/register.html
{% extends "base.html" %}

{% block content %}
<div class="template">
	<div class="form-container">
		<h2>Register</h2>
		<br>
		<form method="POST">
			{% csrf_token %}

			{{ register_form.as_p }}    
			<br>               
			<button type="submit" class="btn btn-dark btn-lg">Register</button>
		</form>
		<p class="text-center">If you already have an account, <a href="{% url "users:login" %}">login</a> instead.</p>
	</div>
</div>
{% endblock %}